@startuml
'https://plantuml.com/sequence-diagram

actor User

participant "Application Layer"     as AL
participant "Domain Layer"          as DL
participant "Infrastructure"        as Inf

/note over AL
    Содержит:
        - реализацию контроллеров
    Ответственность:
        - принять запрос
        - валидация ввода
        - маппинг DTO объектов в Domain Layer и наоборот
        - вызов бизнес логики из Domain Layer
        - вернуть dto пользователю
end note

/note over DL
    Содержит:
        - интерфейсы для взаимодействия с ядром
        - реализация этих интерфейсов (бизнес логика)
        - интерфейсы для взаимодействия
        с внешним миром (repository, web и т.д)

    Доменный слой не знает про существование других слоев

end note

/note over Inf
    Содержит реализацию:
        - репозиториев/кешей
        - интерфейсов для взаимодействия с внешним миром
        - конфигурации бинов и т.д
end note

User -> AL : Пользовательский запрос \nили запрос со стороннего сервиса
AL -> AL : валидирует запрос
AL -> AL : мапит ДТО в сущность \nбизнес модели
AL -> DL : вызов бизнес логики (useCase, service)
DL -> DL : выполняет бизнес логику
DL --> Inf : При необходимости может \nвызывать инфраструктурный слой
DL -> AL
AL -> User

@enduml